/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPerfilRouteImport } from './routes/_app/perfil'
import { Route as AppOnboardingRouteImport } from './routes/_app/onboarding'
import { Route as AppFerramentasRouteImport } from './routes/_app/ferramentas'
import { Route as AdminAdminRouteImport } from './routes/_admin/admin'
import { Route as AppTreinamentosIndexRouteImport } from './routes/_app/treinamentos/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AppTreinamentosIdRouteImport } from './routes/_app/treinamentos/$id'
import { Route as AdminAdminTreinamentosRouteImport } from './routes/_admin/admin/treinamentos'
import { Route as AdminAdminOnboardingRouteImport } from './routes/_admin/admin/onboarding'
import { Route as AdminAdminFerramentasRouteImport } from './routes/_admin/admin/ferramentas'
import { Route as AdminAdminEmpresasRouteImport } from './routes/_admin/admin/empresas'
import { Route as AdminAdminClientesRouteImport } from './routes/_admin/admin/clientes'
import { Route as AdminAdminAvisosRouteImport } from './routes/_admin/admin/avisos'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppFerramentasRoute = AppFerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AdminRoute,
} as any)
const AppTreinamentosIndexRoute = AppTreinamentosIndexRouteImport.update({
  id: '/treinamentos/',
  path: '/treinamentos/',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AppTreinamentosIdRoute = AppTreinamentosIdRouteImport.update({
  id: '/treinamentos/$id',
  path: '/treinamentos/$id',
  getParentRoute: () => AppRoute,
} as any)
const AdminAdminTreinamentosRoute = AdminAdminTreinamentosRouteImport.update({
  id: '/treinamentos',
  path: '/treinamentos',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminOnboardingRoute = AdminAdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFerramentasRoute = AdminAdminFerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminEmpresasRoute = AdminAdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminClientesRoute = AdminAdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminAvisosRoute = AdminAdminAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AdminAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/ferramentas': typeof AppFerramentasRoute
  '/onboarding': typeof AppOnboardingRoute
  '/perfil': typeof AppPerfilRoute
  '/admin/avisos': typeof AdminAdminAvisosRoute
  '/admin/clientes': typeof AdminAdminClientesRoute
  '/admin/empresas': typeof AdminAdminEmpresasRoute
  '/admin/ferramentas': typeof AdminAdminFerramentasRoute
  '/admin/onboarding': typeof AdminAdminOnboardingRoute
  '/admin/treinamentos': typeof AdminAdminTreinamentosRoute
  '/treinamentos/$id': typeof AppTreinamentosIdRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/treinamentos/': typeof AppTreinamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ferramentas': typeof AppFerramentasRoute
  '/onboarding': typeof AppOnboardingRoute
  '/perfil': typeof AppPerfilRoute
  '/admin/avisos': typeof AdminAdminAvisosRoute
  '/admin/clientes': typeof AdminAdminClientesRoute
  '/admin/empresas': typeof AdminAdminEmpresasRoute
  '/admin/ferramentas': typeof AdminAdminFerramentasRoute
  '/admin/onboarding': typeof AdminAdminOnboardingRoute
  '/admin/treinamentos': typeof AdminAdminTreinamentosRoute
  '/treinamentos/$id': typeof AppTreinamentosIdRoute
  '/admin': typeof AdminAdminIndexRoute
  '/treinamentos': typeof AppTreinamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_admin/admin': typeof AdminAdminRouteWithChildren
  '/_app/ferramentas': typeof AppFerramentasRoute
  '/_app/onboarding': typeof AppOnboardingRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/': typeof AppIndexRoute
  '/_admin/admin/avisos': typeof AdminAdminAvisosRoute
  '/_admin/admin/clientes': typeof AdminAdminClientesRoute
  '/_admin/admin/empresas': typeof AdminAdminEmpresasRoute
  '/_admin/admin/ferramentas': typeof AdminAdminFerramentasRoute
  '/_admin/admin/onboarding': typeof AdminAdminOnboardingRoute
  '/_admin/admin/treinamentos': typeof AdminAdminTreinamentosRoute
  '/_app/treinamentos/$id': typeof AppTreinamentosIdRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_app/treinamentos/': typeof AppTreinamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/admin'
    | '/ferramentas'
    | '/onboarding'
    | '/perfil'
    | '/admin/avisos'
    | '/admin/clientes'
    | '/admin/empresas'
    | '/admin/ferramentas'
    | '/admin/onboarding'
    | '/admin/treinamentos'
    | '/treinamentos/$id'
    | '/admin/'
    | '/treinamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/ferramentas'
    | '/onboarding'
    | '/perfil'
    | '/admin/avisos'
    | '/admin/clientes'
    | '/admin/empresas'
    | '/admin/ferramentas'
    | '/admin/onboarding'
    | '/admin/treinamentos'
    | '/treinamentos/$id'
    | '/admin'
    | '/treinamentos'
  id:
    | '__root__'
    | '/_admin'
    | '/_app'
    | '/login'
    | '/reset-password'
    | '/_admin/admin'
    | '/_app/ferramentas'
    | '/_app/onboarding'
    | '/_app/perfil'
    | '/_app/'
    | '/_admin/admin/avisos'
    | '/_admin/admin/clientes'
    | '/_admin/admin/empresas'
    | '/_admin/admin/ferramentas'
    | '/_admin/admin/onboarding'
    | '/_admin/admin/treinamentos'
    | '/_app/treinamentos/$id'
    | '/_admin/admin/'
    | '/_app/treinamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/onboarding': {
      id: '/_app/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ferramentas': {
      id: '/_app/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof AppFerramentasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin': {
      id: '/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/treinamentos/': {
      id: '/_app/treinamentos/'
      path: '/treinamentos'
      fullPath: '/treinamentos/'
      preLoaderRoute: typeof AppTreinamentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_app/treinamentos/$id': {
      id: '/_app/treinamentos/$id'
      path: '/treinamentos/$id'
      fullPath: '/treinamentos/$id'
      preLoaderRoute: typeof AppTreinamentosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_admin/admin/treinamentos': {
      id: '/_admin/admin/treinamentos'
      path: '/treinamentos'
      fullPath: '/admin/treinamentos'
      preLoaderRoute: typeof AdminAdminTreinamentosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/onboarding': {
      id: '/_admin/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminAdminOnboardingRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/ferramentas': {
      id: '/_admin/admin/ferramentas'
      path: '/ferramentas'
      fullPath: '/admin/ferramentas'
      preLoaderRoute: typeof AdminAdminFerramentasRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/empresas': {
      id: '/_admin/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminAdminEmpresasRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/clientes': {
      id: '/_admin/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminAdminClientesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_admin/admin/avisos': {
      id: '/_admin/admin/avisos'
      path: '/avisos'
      fullPath: '/admin/avisos'
      preLoaderRoute: typeof AdminAdminAvisosRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface AdminAdminRouteChildren {
  AdminAdminAvisosRoute: typeof AdminAdminAvisosRoute
  AdminAdminClientesRoute: typeof AdminAdminClientesRoute
  AdminAdminEmpresasRoute: typeof AdminAdminEmpresasRoute
  AdminAdminFerramentasRoute: typeof AdminAdminFerramentasRoute
  AdminAdminOnboardingRoute: typeof AdminAdminOnboardingRoute
  AdminAdminTreinamentosRoute: typeof AdminAdminTreinamentosRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminAvisosRoute: AdminAdminAvisosRoute,
  AdminAdminClientesRoute: AdminAdminClientesRoute,
  AdminAdminEmpresasRoute: AdminAdminEmpresasRoute,
  AdminAdminFerramentasRoute: AdminAdminFerramentasRoute,
  AdminAdminOnboardingRoute: AdminAdminOnboardingRoute,
  AdminAdminTreinamentosRoute: AdminAdminTreinamentosRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminRoute: AdminAdminRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppFerramentasRoute: typeof AppFerramentasRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTreinamentosIdRoute: typeof AppTreinamentosIdRoute
  AppTreinamentosIndexRoute: typeof AppTreinamentosIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFerramentasRoute: AppFerramentasRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
  AppTreinamentosIdRoute: AppTreinamentosIdRoute,
  AppTreinamentosIndexRoute: AppTreinamentosIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
